name: Run tests

on:
  push:
    branches: [main]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install server dependencies
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: server
      - name: Install web dependencies
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: web
      - name: Component & API & UI tests
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: web
          install: false
          start: yarn start:ci
          wait-on: 'http://localhost:3000'
